create table public.products (
    id integer generated by default as identity not null,
    "Name" character varying null,
    "Price" character varying null,
    "Stock" bigint null,
    "Deskripsi" character varying null,
    create_at timestamp without time zone null default now(),
    update_at timestamp without time zone null,
    id_merek integer null,
    constraint products_pkey primary key (id),
    constraint products_id_merek_fkey foreign KEY (id_merek) references merek (id)
) TABLESPACE pg_default;