create table public.merek (
    id integer generated by default as identity not null,
    name character varying null,
    deskripsi character varying null,
    constraint merek_pkey primary key (id)
) TABLESPACE pg_default;